name: Publish

on:
  push:
    paths:
      - lead/package.json
      - package.json

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: |
          npm i -g pnpm
          pnpm i

          cd lead
          pnpm i
          cd ..

          pnpm build:release
        env:
          VSCE_PAT: ${{ secrets.VSCODE_TOKEN }}
